### ISSUE TITLE
Where are the instructions?

### ISSUE THREAD

**Issue by stonecrusher** [jeremyperkin/uBlockdark#1]
The readme says "PLEASE FOLLOW THE BELOW INSTRUCTIONS!"
But there are no instructions besides making a backup...

In Firefox I don't have a ublock folder, but know about modifying css via userChrome.css
Further instructions appreciated.

**Comment by jeremyperkin** [comment]
I have not done anything with this for QUITE some time now.

**Comment by stonecrusher** [comment]
I can't tell if it would need an update if I don't know how to install it at all.

**Comment by jeremyperkin** [comment]
This was has not been worked on in over a year.

uBlock Origin has been updated to include the coding necessary for dark UI.

Currently you might want to check uBlock Origin for what has been done with this information.

Alternatively you can always check out r/FirefoxCSS where this code has been sitting 

https://www.reddit.com/r/FirefoxCSS/wiki/index/uubo/

If you understand how to customize Firefox you will be good to go.  If not you might need to engage with the community there.

**Comment by jeremyperkin** [comment]
Grab https://github.com/gorhill/uBlock/releases

The DEV release has dark mode included.  Just have to change the theme to dark.

**Comment by stonecrusher** [comment]
uBO dev release with `uiTheme dark` checks out. Thanks.
Although Codemirror seems to need an update (readability of focused line).
